# Firm names
BUSINESS_NAME = "ELECTRO INDUSTRIAL SANT FELIU, S.L."
BUSINESS_SHORT_NAME = "EISSA"

# Color names
LIGHT_BLUE = "lightblue"
BROWN_COLOR = "#6B4423"
KHAKI_COLOR = "darkkhaki"
YELLOW_COLOR = "#FFF68F"
METAL_GOLD_COLOR =  "#D4AF37"
BEIGE_COLOR = "#AB9C89"
LIGHT_GRAY_COLOR = "#778899"
MEDIUM_GRAY_COLOR = "#808080"
WHITE_COLOR = "#FFFFFF"
BLACK_COLOR = "#000000"
GREEN_COLOR = "#4F7942"